language: cpp

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo apt-get -qq install libprotobuf-dev
  - sudo apt-get -qq install protobuf-compiler
  - sudo apt-get -qq install libsnappy-dev
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "brew update 2>&1 > /brew-update.txt || (cat /brew-update.txt && false)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cask; fi


install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install java; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=/Library/Java/Home; fi
  - cd $TRAVIS_BUILD_DIR/java
  - mvn package

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..

script:
  - make package -j2
  - make test-out 2>&1 > /test-out.txt

branches:
  except:
    - legacy
