language: cpp

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRIVIS_OS_NAME" == "osx" ]]; then "brew update 2>&1 > /tmp/brew-update.txt || (cat /tmp/brew-update.txt && false)"; fi
  - if [[ "$TRIVIS_OS_NAME" == "osx" ]]; then brew install cask; fi


install:
  - if [[ "$TRIVIS_OS_NAME" == "osx" ]]; then brew cask install java; fi
#- if [[ "$TRIVIS_OS_NAME" == "osx" ]]; then brew outdated maven || brew upgrade maven; fi
  - cd $TRAVIS_BUILD_DIR/java
  - mvn package

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..

script:
  - if [[ "$TRIVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=/Library/Java/Home; fi
  - make package -j2
  - make test-out 2>&1 > /tmp/test-out.txt

branches:
  except:
    - legacy
